"""Add stripe_account_id to owner

Revision ID: 1657a773ccb2
Revises: 8595bb4b9d0a
Create Date: 2025-04-25 00:47:15.124158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1657a773ccb2'
down_revision: Union[str, None] = '8595bb4b9d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owner', sa.Column('stripe_account_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owner', 'stripe_account_id')
    # ### end Alembic commands ###
