"""Add rating, views, and amenities to Hotel

Revision ID: 72efce92e92e
Revises: d2bfa3de8452
Create Date: 2025-01-18 14:53:16.624595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72efce92e92e'
down_revision: Union[str, None] = 'd2bfa3de8452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('hotels', sa.Column('rating_count', sa.Integer(), nullable=True))
    op.add_column('hotels', sa.Column('views', sa.Integer(), nullable=True))
    op.add_column('hotels', sa.Column('amenities', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'amenities')
    op.drop_column('hotels', 'views')
    op.drop_column('hotels', 'rating_count')
    op.drop_column('hotels', 'rating')
    # ### end Alembic commands ###
