"""Add description to Hotel and Room

Revision ID: 770862ffc85e
Revises: df73a963fd97
Create Date: 2025-01-20 22:30:14.405920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '770862ffc85e'
down_revision: Union[str, None] = 'df73a963fd97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('rooms', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'description')
    op.drop_column('hotels', 'description')
    # ### end Alembic commands ###
