"""add avatar_url to people

Revision ID: 78d4a26321ba
Revises: c083412a20a2
Create Date: 2025-01-29 18:14:01.811796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78d4a26321ba'
down_revision: Union[str, None] = 'c083412a20a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('avatar_url', sa.String(), nullable=True))
    op.drop_column('people', 'profile_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('profile_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('people', 'avatar_url')
    # ### end Alembic commands ###
