"""Added Payment table and booking modifications

Revision ID: 80373b8ef5cb
Revises: 78d4a26321ba
Create Date: 2025-03-08 20:16:34.078568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80373b8ef5cb'
down_revision: Union[str, None] = '78d4a26321ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('payment_id', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('status', sa.String(), nullable=False))
    op.add_column('bookings', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('bookings', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'payments', ['payment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'paid_at')
    op.drop_column('bookings', 'created_at')
    op.drop_column('bookings', 'status')
    op.drop_column('bookings', 'payment_id')
    # ### end Alembic commands ###
