"""add room_number_snapshot to Booking

Revision ID: 86789b6fde6e
Revises: 308249e9b397
Create Date: 2025-05-09 12:05:58.801031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86789b6fde6e'
down_revision: Union[str, None] = '308249e9b397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'bookings',
        sa.Column('room_number_snapshot', sa.String(length=10), nullable=False, server_default='deleted')
    )

    op.drop_constraint('hotels_address_id_fkey', 'hotels', type_='foreignkey')
    op.create_foreign_key(None, 'hotels', 'addresses', ['address_id'], ['id'], ondelete='CASCADE')
    op.alter_column('payments', 'booking_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('payments_booking_id_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_booking_id_fkey', 'payments', 'bookings', ['booking_id'], ['id'], ondelete='SET NULL')
    op.alter_column('payments', 'booking_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'hotels', type_='foreignkey')
    op.create_foreign_key('hotels_address_id_fkey', 'hotels', 'addresses', ['address_id'], ['id'])
    op.drop_column('bookings', 'room_number_snapshot')
    # ### end Alembic commands ###
